### ISSUE TITLE
Non Discovery Usage?

### ISSUE THREAD

**Issue by LeeThompson** [baierjan/Device-Yeelight#1]
There is no real documentation on Device::Yeelight::Light, if the IP and port of the light is known, is it possible to just open a connection to it?

**Comment by baierjan** [comment]
It should be possible to use something like:

```pl
my $light = Device::Yeelight::Light->new(location => 'yeelight://192.168.1.100:55443');
$light->set_power('on', 'sudden', 0, 5);
```
