### ISSUE TITLE
Sample Fails (Strawberry Perl 5.32.1)

### ISSUE THREAD

**Issue by LeeThompson** [baierjan/Device-Yeelight#2]
The main code sample in the .pod does not work.  (Discovery.pl does however.)

```
String found where operator expected at test.pl line 7, near "say "The light is $props{power}""
        (Do you need to predeclare say?)
syntax error at test.pl line 7, near "say "The light is $props{power}""
Execution of test.pl aborted due to compilation errors.
```

**Comment by baierjan** [comment]
Thank you for letting me know. You need "say" feature enabled, that was done with the line `use 5.026` in the example (which is sadly missing in the pod), you can also `use feature 'say'` (see: https://perldoc.perl.org/functions/say). I will update the pod to include this.
